// GENERATED by cmd/golden6 — do not edit by hand.
//
// Pins the six games added by migration 000032 to the Go engines they mirror.
// The logs below were played by a bot against the Go implementation; replaying
// them here has to produce the identical score and stats. A difference means
// the app would show a player one number and the server would bank another.

import 'package:flutter_test/flutter_test.dart';

import 'package:send_agift_mobile/features/games/domain/bubble_shooter.dart';
import 'package:send_agift_mobile/features/games/domain/doodle_jump.dart';
import 'package:send_agift_mobile/features/games/domain/fruit_slice.dart';
import 'package:send_agift_mobile/features/games/domain/memory_match.dart';
import 'package:send_agift_mobile/features/games/domain/tower_blocks.dart';
import 'package:send_agift_mobile/features/games/domain/whack_a_mole.dart';

const seed = '5f3a91c2';

void main() {
  test('memory match matches the Go engine', () {
    // Go: score=440 best_streak=8 matches=8 turns=9
    const moves = ['4', '1', '4', '11', '1', '2', '5', '6', '8', '14', '12', '15', '7', '10', '0', '9', '3', '13'];
    final game = MemoryMatch(seed: seed, config: const MemoryConfig());
    for (final move in moves) {
      game.flip(int.parse(move));
    }
    expect(game.score, 440);
    expect(game.matches, 8);
    expect(game.turns, 9);
    expect(game.bestStreak, 8);
    expect(game.moves, moves);
  });

  test('whack-a-mole matches the Go engine', () {
    // Go: score=2304 best_streak=32 hits=32 misses=0
    const moves = ['10:1', '68:0', '131:4', '238:0', '296:2', '347:7', '399:2', '500:0', '553:0', '605:1', '650:8', '745:3', '791:6', '840:3', '886:3', '971:0', '1010:4', '1050:8', '1093:7', '1168:4', '1200:8', '1239:8', '1275:8', '1338:8', '1373:2', '1403:0', '1435:0', '1497:6', '1527:7', '1557:7', '1591:7', '1655:3'];
    final game = WhackAMole(seed: seed, config: const WhackConfig());
    for (final move in moves) {
      final parts = move.split(':');
      final at = int.parse(parts[0]);
      while (game.tick < at && !game.isOver) {
        game.advance();
      }
      game.whack(int.parse(parts[1]));
    }
    expect(game.score, 2304);
    expect(game.hits, 32);
    expect(game.bestStreak, 32);
    expect(game.moves, moves);
  });

  test('bubble shooter matches the Go engine', () {
    // Go: score=580 best_combo=2 pops=50 shots=30
    const moves = ['3', '0', '1', '2', '3', '3', '3', '3', '4', '0', '0', '0', '0', '1', '1', '6', '0', '4', '1', '5', '0', '3', '5', '0', '1', '0', '5', '5', '6', '0'];
    final game = BubbleShooter(seed: seed, config: const BubbleConfig());
    for (final move in moves) {
      game.shoot(int.parse(move));
    }
    expect(game.score, 580);
    expect(game.pops, 50);
    expect(game.bestCombo, 2);
    expect(game.moves, moves);
  });

  test('tower blocks matches the Go engine', () {
    // Go: score=640 best_combo=1 placed=40 rows=12
    const moves = ['0', '2', '4', '0', '3', '0', '5', '5', '2', '3', '0', '3', '4', '0', '3', '0', '1', '2', '5', '0', '3', '4', '0', '2', '0', '3', '0', '3', '5', '5', '0', '1', '4', '0', '5', '3', '5', '0', '1', '2'];
    final game = TowerBlocks(seed: seed, config: const TowerBlocksConfig());
    for (final move in moves) {
      game.drop(int.parse(move));
    }
    expect(game.score, 640);
    expect(game.rowsCleared, 12);
    expect(game.pieces, 40);
    expect(game.moves, moves);
  });

  test('fruit slice matches the Go engine', () {
    // Go: score=5670 best_streak=42 fruits=42
    const moves = ['14:1', '95:3', '178:2', '259:1', '332:0', '409:4', '486:0', '632:4', '703:3', '768:3', '833:1', '904:1', '967:2', '1103:4', '1168:0', '1227:3', '1284:3', '1351:4', '1406:4', '1532:1', '1595:4', '1658:0', '1713:1', '1772:3', '1831:1', '1935:2', '1984:2', '2039:0', '2092:1', '2137:4', '2186:4', '2280:0', '2319:4', '2369:3', '2410:3', '2450:4', '2495:4', '2588:4', '2630:4', '2669:0', '2709:3', '2756:0'];
    final game = FruitSlice(seed: seed, config: const FruitConfig());
    for (final move in moves) {
      final parts = move.split(':');
      final at = int.parse(parts[0]);
      while (game.tick < at && !game.isOver) {
        game.advance();
      }
      game.slice(int.parse(parts[1]));
    }
    expect(game.score, 5670);
    expect(game.sliced, 42);
    expect(game.bestStreak, 42);
    expect(game.moves, moves);
  });

  test('doodle jump matches the Go engine', () {
    // Go: score=476 height=44 hops=40 springs=4
    const moves = ['0', '0', '0', '0', '1', '2', '1', '0', '0', '1', '2', '1', '2', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '2', '2', '3', '2', '3', '4', '4'];
    final game = DoodleJump(seed: seed, config: const DoodleConfig());
    for (final move in moves) {
      game.hop(int.parse(move));
    }
    expect(game.score, 476);
    expect(game.height, 44);
    expect(game.hops, 40);
    expect(game.springs, 4);
    expect(game.moves, moves);
  });
}
